---
- hosts: test-area
  remote_user: root

  tasks:
    - name: install nginx
      yum: name=nginx state=latest
    - name: defined nginx config file
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify: set nginx service restart
    - name: defined nginx service started
      service: name=nginx state=started enabled=yes

  handlers:
    - name: set nginx service restart
      service: name=nginx state=restarted
